# modify1
version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Setup AWS CLI
          command: |
            curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"
            unzip awscli-bundle.zip
            sudo ./awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws
  deploy_job:
    machine: true
    steps:
      - checkout
      - run:
          name: Deploy
          command: |
            mkdir  -p ~/.aws
            echo "[hiraki]" > ~/.aws/credentials
            echo "aws_access_key_id = AKIASYQFHUYM7XX4BKFM" >>  ~/.aws/credentials
            echo "aws_secret_access_key = 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" >>  ~/.aws/credentials
            echo "region = ap-northeast-1" >>  ~/.aws/credentials
            eval $(aws ecr get-login --no-include-email --region ap-northeast-1)
            docker build -t sample-hiraki .
            docker tag sample-hiraki:latest 190063289881.dkr.ecr.ap-northeast-1.amazonaws.com/sample-hiraki:latest
            docker push 190063289881.dkr.ecr.ap-northeast-1.amazonaws.com/sample-hiraki:latest
            aws ecs update-service --cluster hiraki-test-20190411 --service sample-hiraki-1 --profile hiraki
workflows:
  version: 2
  Deploy:
    jobs:
      - build
      - deploy_job