version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Setup common environment variables
          command: |
            echo 'export ECR_REPOSITORY_NAME="${AWS_RESOURCE_NAME_PREFIX}"' >> $BASH_ENV
            echo 'export FULL_IMAGE_NAME="${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${ECR_REPOSITORY_NAME}:${CIRCLE_SHA1}"' >> $BASH_ENV
      - run:
          name: Setup AWS CLI
          command: |
            curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"
            unzip awscli-bundle.zip
            sudo ./awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws
      - run:
          name: aws configure
          command: |
            aws configure set aws_access_key_id AKIASYQFHUYM7ZHTU6EJ --profile hiraki
            aws configure set aws_secret_access_key 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 --profile hiraki
      - run:
          name: ECR Login
          command: |
            eval $(aws ecr get-login --no-include-email --region ap-northeast-1)    
      - run:
          name: Build Image
          command: |
            docker build -t sample-hiraki .
      - run:
          name: Login to AWS ECR
          command: eval $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - run:
          name: tag setting
          command: |
             docker tag sample-hiraki:latest 190063289881.dkr.ecr.ap-northeast-1.amazonaws.com/sample-hiraki:latest
      - run:
          name: docker push
          command: |
             docker push 190063289881.dkr.ecr.ap-northeast-1.amazonaws.com/sample-hiraki:latest       


