version: 2

jobs:
  build:
    steps:
      - checkout
      - run:
          name: Setup common environment variables
          command: |
            mkdir  -p ~/.aws
            echo "[hiraki]" > ~/.aws/credentials
            echo "aws_access_key_id = AKIASYQFHUYM7ZHTU6EJ" >>  ~/.aws/credentials
            echo "aws_secret_access_key = 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" >>  ~/.aws/credentials
            echo "region = ap-northeast-1" >>  ~/.aws/credentials

      - run:
          name: Setup AWS CLI
          command: |
            curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"
            unzip awscli-bundle.zip
            sudo ./awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws
  deploy_job:
    steps:
      - run:
          name: Deploy
          command: |
            eval $(aws ecr get-login --no-include-email --region ap-northeast-1)
            docker build -t sample-hiraki .
            docker tag sample-hiraki:latest 190063289881.dkr.ecr.ap-northeast-1.amazonaws.com/sample-hiraki:latest
            docker push 190063289881.dkr.ecr.ap-northeast-1.amazonaws.com/sample-hiraki:latest
workflows:
  version: 2
  Deploy:
    jobs:
      - build:
      - deploy_job:
        filters:
          branches:
            only: deploy